analysis_spec:
- CRF: rawplus_dm
  DataField: age_nsv
  DataType: Num
  Missing: 'Y'
  Outlier: 'Y'
  Digit: 'Y'
  Variant: 'Y'
- CRF: rawplus_dm
  DataField: sex
  DataType: Chr
  Missing: 'Y'
  Outlier: ''
  Digit: ''
  Variant: ''
- CRF: rawplus_dm
  DataField: timeontreatment
  DataType: Num
  Missing: 'Y'
  Outlier: 'Y'
  Digit: 'Y'
  Variant: 'Y'
- CRF: rawplus_dm
  DataField: timeonstudy
  DataType: Num
  Missing: 'Y'
  Outlier: 'Y'
  Digit: 'Y'
  Variant: 'Y'
